version: '3.4'

services:
  server:
    container_name: example-server
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/var/www/example-server
    tty: true
    depends_on:
      - sqlite3
    networks:
      - example-network
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    networks:
      - example-network
    volumes:
      - ./db/:/root/db/

networks:
  example-network:
    external: true
